/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Activities {
  actor_user_id: string | null;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  kind: string;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  summary: string;
}

export interface AdjustmentIndices {
  granularity: string;
  key: string;
  name: string;
  source: string;
}

export interface AiConversations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  last_message_at: Generated<Timestamp>;
  mode: string;
  module: string | null;
  organization_id: string;
  user_id: string;
}

export interface AiFeedback {
  comment: string | null;
  created_at: Generated<Timestamp>;
  feature: string | null;
  id: Generated<string>;
  interaction_id: string | null;
  message_id: string | null;
  organization_id: string;
  prompt_ref: string | null;
  rating: number;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AiInteractions {
  ai_conversation_id: string | null;
  cache_creation_input_tokens: number | null;
  cache_read_input_tokens: number | null;
  conversation_id: string | null;
  cost_usd_micros: Int8 | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  fallback_reason: string | null;
  feature: string | null;
  guard_violations: Generated<Json>;
  handoff_reason: string | null;
  id: Generated<string>;
  input_tokens: number | null;
  latency_ms: number | null;
  message_id: string | null;
  model: string;
  organization_id: string | null;
  output_tokens: number | null;
  prompt_version: string;
  provider: string | null;
  purpose: string;
  request_id: string | null;
  retrieval_count: number | null;
  retrieval_failed: Generated<boolean>;
  rounds: number | null;
  status: string;
  stop_reason: string | null;
  task: string | null;
  tool_calls: Generated<Json>;
  tool_failures: Generated<number>;
  user_id: string | null;
}

export interface AiKnowledgeChunks {
  anchor: string;
  body: string;
  content_hash: string;
  created_at: Generated<Timestamp>;
  document_id: string;
  heading: string;
  id: Generated<string>;
  ordinal: number;
  permissions: Generated<string[]>;
  route: string | null;
  search: Generated<string | null>;
  updated_at: Generated<Timestamp>;
}

export interface AiKnowledgeDocuments {
  chunk_count: Generated<number>;
  content_hash: string;
  created_at: Generated<Timestamp>;
  domain: string;
  id: Generated<string>;
  organization_id: string | null;
  path: string;
  summary: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface AiMessages {
  content: string;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  interaction_id: string | null;
  payload: Generated<Json>;
  prompt_ref: string | null;
  role: string;
}

export interface Appointments {
  assigned_user_id: string;
  cancel_reason: string | null;
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ends_at: Timestamp;
  follow_up_task_id: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  kind: string;
  lead_id: string | null;
  location: string | null;
  notes: string | null;
  opportunity_id: string | null;
  property_id: string | null;
  result: string | null;
  starts_at: Timestamp;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface AuditLogs {
  action: string;
  actor_kind: string;
  actor_user_id: string | null;
  after: Json | null;
  before: Json | null;
  entity_id: string | null;
  entity_type: string;
  id: Generated<Int8>;
  ip: string | null;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  request_id: string | null;
}

export interface AutomationDefinitions {
  actions: Json;
  conditions: Generated<Json>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_enabled: Generated<boolean>;
  is_system: Generated<boolean>;
  key: string;
  name: string;
  trigger_event: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AutomationErrors {
  attempt: number | null;
  automation_key: string | null;
  error: string | null;
  finished_at: Timestamp | null;
  id: string | null;
  started_at: Timestamp | null;
  trigger_event_id: Int8 | null;
}

export interface AutomationRuns {
  attempt: Generated<number>;
  automation_id: string;
  automation_version: number;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  input: Generated<Json>;
  result: Json | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  trigger_event_id: Int8;
}

export interface Branches {
  address_number: string | null;
  address_street: string | null;
  city: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_main: Generated<boolean>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string;
  organization_id: string;
  phone: string | null;
  province: string | null;
  schedule: string | null;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface Campaigns {
  budget_amount: Numeric | null;
  budget_currency: string | null;
  channel: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ends_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  starts_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  utm_campaign: string | null;
}

export interface ContactAddresses {
  city: string | null;
  contact_id: string;
  country: Generated<string | null>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label: string | null;
  number: string | null;
  postal_code: string | null;
  province: string | null;
  street: string | null;
}

export interface ContactDuplicateCandidates {
  contact_a: string;
  contact_b: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reason: string;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  score: Numeric;
  status: Generated<string>;
}

export interface ContactEmails {
  contact_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  email_normalized: string;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  label: string | null;
}

export interface ContactPhones {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  is_whatsapp: Generated<boolean>;
  label: string | null;
  phone_e164: string | null;
  phone_raw: string;
}

export interface ContactRoles {
  contact_id: string;
  created_at: Generated<Timestamp>;
  role: string;
}

export interface Contacts {
  assigned_user_id: string | null;
  company_name: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  display_name: string;
  document_number: string | null;
  document_type: string | null;
  first_name: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  kind: Generated<string>;
  last_name: string | null;
  merged_into_id: string | null;
  organization_id: string;
  source: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ContactTags {
  contact_id: string;
  tag_id: string;
}

export interface ContentTemplates {
  body: string;
  channel: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface ConversationMessages {
  attempts: Generated<number>;
  body: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  direction: string;
  error: string | null;
  error_code: string | null;
  external_message_id: string | null;
  failed_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string | null;
  kind: Generated<string>;
  payload: Generated<Json>;
  read_at: Timestamp | null;
  reply_to_message_id: string | null;
  sender_kind: string;
  sender_user_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<string>;
  status_updated_at: Timestamp | null;
}

export interface Conversations {
  ai_failures: Generated<number>;
  assigned_user_id: string | null;
  channel: string;
  closed_at: Timestamp | null;
  collected: Generated<Json>;
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  external_thread_id: string;
  handoff_at: Timestamp | null;
  handoff_reason: string | null;
  id: Generated<string>;
  last_inbound_at: Timestamp | null;
  last_message_at: Timestamp | null;
  last_outbound_at: Timestamp | null;
  mode: Generated<string>;
  summary: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DomainEvents {
  actor_user_id: string | null;
  aggregate_id: string;
  aggregate_type: string;
  dedupe_key: string | null;
  dispatch_attempts: Generated<number>;
  dispatched_at: Timestamp | null;
  event_type: string;
  id: Generated<Int8>;
  last_error: string | null;
  occurred_at: Generated<Timestamp>;
  payload: Generated<Json>;
}

export interface ExternalRefs {
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  external_id: string;
  external_type: string;
  id: Generated<string>;
  source: string;
}

export interface FeatureFlags {
  description: string;
  enabled: Generated<boolean>;
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Features {
  grp: string;
  id: Generated<string>;
  key: string;
  name: string;
  sort_order: Generated<number>;
}

export interface Files {
  bucket: string;
  checksum_sha256: string | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  height: number | null;
  id: Generated<string>;
  original_name: string | null;
  size_bytes: Int8;
  storage_driver: string;
  storage_key: string;
  storage_removed_at: Timestamp | null;
  uploaded_by: string | null;
  visibility: string;
  width: number | null;
}

export interface IndexValues {
  entered_by: string | null;
  fetched_at: Generated<Timestamp>;
  index_key: string;
  period_date: string;
  source: string;
  /**
   * Diarios (ICL/CER): valor publicado del día. Mensuales (IPC/CASA_PROPIA): coeficiente 1 + variación mensual/100, period_date = día 1.
   */
  value: Numeric;
}

export interface IntegrationCredentials {
  access_expires_at: Timestamp | null;
  auth_tag: string;
  ciphertext: string;
  integration_key: string;
  iv: string;
  rotated_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface IntegrationLogs {
  created_at: Generated<Timestamp>;
  duration_ms: number | null;
  entity_id: string | null;
  entity_type: string | null;
  error: string | null;
  http_status: number | null;
  id: Generated<Int8>;
  integration_key: string;
  metadata: Generated<Json>;
  operation: string;
  request_id: string | null;
  status: string;
}

export interface Integrations {
  category: string;
  circuit_open_until: Timestamp | null;
  config: Generated<Json>;
  consecutive_failures: Generated<number>;
  key: string;
  last_error: string | null;
  last_error_at: Timestamp | null;
  last_ok_at: Timestamp | null;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  lease_expires_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Generated<Json>;
  priority: Generated<number>;
  result: Json | null;
  run_at: Generated<Timestamp>;
  started_at: Timestamp | null;
  status: Generated<string>;
  timeout_ms: Generated<number>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Leads {
  assigned_at: Timestamp | null;
  assigned_user_id: string | null;
  branch_id: string | null;
  campaign_id: string | null;
  contact_id: string;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  external_id: string | null;
  first_response_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string | null;
  message: string | null;
  operation_interest: string | null;
  organization_id: string;
  priority: Generated<string>;
  property_id: string | null;
  source_key: string;
  status: Generated<string>;
  submitted_email: string | null;
  submitted_phone: string | null;
  updated_at: Generated<Timestamp>;
  utm: Generated<Json>;
}

export interface LeadSources {
  channel: string;
  is_active: Generated<boolean>;
  key: string;
  name: string;
}

export interface Locations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  name: string;
  parent_id: string | null;
  slug: string;
}

export interface LoginAttempts {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  ip: string | null;
  success: boolean;
}

export interface MigrationRecords {
  error: string | null;
  external_id: string;
  first_seen_at: Generated<Timestamp>;
  id: Generated<string>;
  last_run_id: string;
  normalized: Json | null;
  property_id: string | null;
  raw: Json | null;
  raw_hash: string | null;
  source: string;
  stage: string;
  updated_at: Generated<Timestamp>;
}

export interface MigrationRuns {
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  options: Generated<Json>;
  source: string;
  started_at: Generated<Timestamp>;
  stats: Generated<Json>;
  status: Generated<string>;
  triggered_by: string;
}

export interface MigrationWarnings {
  code: string;
  created_at: Generated<Timestamp>;
  external_id: string;
  field: string;
  id: Generated<string>;
  message: string;
  property_id: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  run_id: string;
  severity: string;
  source: string;
  status: Generated<string>;
  value_a: string | null;
  value_b: string | null;
}

export interface Notes {
  author_user_id: string | null;
  body: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  entity_id: string;
  entity_type: string;
  id: Generated<string>;
  idempotency_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  body: string | null;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  kind: string;
  link: string | null;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface Opportunities {
  assigned_user_id: string | null;
  budget_currency: string | null;
  budget_max: Numeric | null;
  budget_min: Numeric | null;
  closed_at: Timestamp | null;
  contact_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  expected_close_date: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  lead_id: string | null;
  lost_reason: string | null;
  operation: string | null;
  organization_id: string;
  pipeline_id: string;
  property_id: string | null;
  requirements: Generated<Json>;
  stage_entered_at: Generated<Timestamp>;
  stage_id: string;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  value_amount: Numeric | null;
  value_currency: string | null;
}

export interface OpportunityStageHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  from_stage_id: string | null;
  id: Generated<Int8>;
  note: string | null;
  opportunity_id: string;
  to_stage_id: string;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  founded_year: number | null;
  id: Generated<string>;
  legal_name: string | null;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface OutboundMessages {
  attempts: Generated<number>;
  channel: string;
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  last_error: string | null;
  payload: Generated<Json>;
  provider_message_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<string>;
  subject: string | null;
  template_key: string;
  to_address: string;
  updated_at: Generated<Timestamp>;
}

export interface OwnerReports {
  data: Json;
  file_id: string | null;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  id: Generated<string>;
  last_error: string | null;
  owner_contact_id: string;
  period_end: string;
  period_start: string;
  property_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<string>;
}

export interface OwnerSettlements {
  approved_at: Timestamp | null;
  approved_by: string | null;
  cancelled_reason: string | null;
  contract_id: string;
  currency: string;
  generated_at: Generated<Timestamp>;
  generated_by: string | null;
  gross_collected: Numeric;
  id: Generated<string>;
  management_fee_amount: Numeric;
  net_amount: Numeric;
  other_deductions: Generated<Numeric>;
  owner_contact_id: string;
  paid_at: Timestamp | null;
  period_start: string;
  status: Generated<string>;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Permissions {
  description: string;
  key: string;
  module: string;
}

export interface Pipelines {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  key: string;
  kind: string;
  name: string;
}

export interface PipelineStages {
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  name: string;
  outcome: Generated<string>;
  pipeline_id: string;
  sort_order: number;
}

export interface Properties {
  address_floor: string | null;
  address_number: string | null;
  address_street: string | null;
  address_unit: string | null;
  age_years: number | null;
  allows_pets: boolean | null;
  archived_at: Timestamp | null;
  attributes: Generated<Json>;
  bathrooms: number | null;
  bedrooms: number | null;
  branch_id: string | null;
  code: number;
  condition: string | null;
  covered_area_m2: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credit_eligible: boolean | null;
  deleted_at: Timestamp | null;
  description: string | null;
  disposition: string | null;
  featured: Generated<boolean>;
  garages: number | null;
  hide_exact_address: Generated<boolean>;
  id: Generated<string>;
  imported_at: Timestamp | null;
  is_demo: Generated<boolean>;
  is_published: Generated<boolean>;
  land_area_m2: Numeric | null;
  last_synced_at: Timestamp | null;
  latitude: Numeric | null;
  location_id: string | null;
  longitude: Numeric | null;
  manually_verified_at: Timestamp | null;
  manually_verified_by: string | null;
  organization_id: string;
  orientation: string | null;
  professional_use: boolean | null;
  protected_fields: Generated<string[]>;
  published_at: Timestamp | null;
  rooms: number | null;
  seo_description: string | null;
  seo_title: string | null;
  slug: string;
  source: Generated<string>;
  status: Generated<string>;
  title: string;
  toilets: number | null;
  total_area_m2: Numeric | null;
  type_key: string;
  uncovered_area_m2: Numeric | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PropertyAgents {
  created_at: Generated<Timestamp>;
  property_id: string;
  role: Generated<string>;
  user_id: string;
}

export interface PropertyDocuments {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  file_id: string;
  id: Generated<string>;
  kind: string;
  property_id: string;
  title: string;
  uploaded_by: string | null;
  visible_to_owner: Generated<boolean>;
}

export interface PropertyFeatures {
  feature_id: string;
  property_id: string;
}

export interface PropertyMedia {
  alt_text: string | null;
  copy_attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  file_id: string | null;
  height: number | null;
  id: Generated<string>;
  is_cover: Generated<boolean>;
  kind: string;
  last_checked_at: Timestamp | null;
  last_error: string | null;
  original_file_id: string | null;
  property_id: string;
  sort_order: Generated<number>;
  source_url: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  width: number | null;
}

export interface PropertyOperations {
  amount: Numeric | null;
  created_at: Generated<Timestamp>;
  currency: string;
  expenses_amount: Numeric | null;
  expenses_currency: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  operation: string;
  price_hidden: Generated<boolean>;
  property_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PropertyOwners {
  contact_id: string;
  created_at: Generated<Timestamp>;
  is_primary: Generated<boolean>;
  property_id: string;
  share_pct: Numeric | null;
  since: string | null;
  until: string | null;
}

export interface PropertyPriceHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  id: Generated<Int8>;
  new_amount: Numeric | null;
  new_currency: string;
  operation: string;
  previous_amount: Numeric | null;
  previous_currency: string | null;
  property_id: string;
  reason: string | null;
  source: string;
}

export interface PropertyPublications {
  attempts: Generated<number>;
  channel_key: string;
  created_at: Generated<Timestamp>;
  desired_state: string;
  external_id: string | null;
  external_url: string | null;
  id: Generated<string>;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  last_payload_hash: string | null;
  last_synced_at: Timestamp | null;
  property_id: string;
  remote_write_started_at: Timestamp | null;
  sync_locked_until: Timestamp | null;
  sync_status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PropertyRedirects {
  created_at: Generated<Timestamp>;
  path: string;
  property_id: string;
}

export interface PropertyStatusHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  from_status: string | null;
  id: Generated<Int8>;
  property_id: string;
  reason: string | null;
  to_status: string;
}

export interface PropertyTypes {
  category: string;
  field_schema: Generated<Json>;
  is_active: Generated<boolean>;
  key: string;
  name: string;
  name_plural: string;
  sort_order: Generated<number>;
}

export interface PublicationChannels {
  integration_key: string | null;
  is_enabled: Generated<boolean>;
  key: string;
  kind: string;
  name: string;
}

export interface RateLimitBuckets {
  count: Generated<number>;
  key: string;
  window_start: Timestamp;
}

export interface RentAdjustments {
  applied_at: Timestamp | null;
  applied_by: string | null;
  calculated_at: Generated<Timestamp>;
  calculated_by: string | null;
  calculation: Generated<Json>;
  contract_id: string;
  effective_date: string;
  factor: Numeric;
  id: Generated<string>;
  index_end_date: string | null;
  index_end_value: Numeric | null;
  index_key: string | null;
  index_start_date: string | null;
  index_start_value: Numeric | null;
  method: string;
  new_amount: Numeric;
  note: string | null;
  previous_amount: Numeric;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  rejected_reason: string | null;
  status: Generated<string>;
}

export interface RentalContractDocuments {
  contract_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  file_id: string;
  id: Generated<string>;
  kind: string;
  title: string;
  uploaded_by: string | null;
  visible_to_owner: Generated<boolean>;
}

export interface RentalContractParties {
  contact_id: string;
  contract_id: string;
  role: string;
  share_pct: Numeric | null;
}

export interface RentalContracts {
  adjustment_checked_at: Timestamp | null;
  adjustment_index_key: string | null;
  adjustment_pending_note: string | null;
  adjustment_period_months: number | null;
  code: string;
  commission_amount: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string;
  current_rent: Numeric;
  deposit_amount: Numeric | null;
  deposit_currency: string | null;
  end_date: string;
  ended_reason: string | null;
  id: Generated<string>;
  initial_rent: Numeric;
  late_fee_daily_pct: Numeric | null;
  management_fee_pct: Generated<Numeric>;
  next_adjustment_date: string | null;
  notes: string | null;
  organization_id: string;
  payment_due_day: Generated<number>;
  property_id: string;
  renewal_of_contract_id: string | null;
  start_date: string;
  status: Generated<string>;
  terminated_at: Timestamp | null;
  termination_reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RentObligations {
  amount: Numeric;
  concept: Generated<string>;
  contract_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  due_date: string;
  id: Generated<string>;
  paid_amount: Generated<Numeric>;
  period_start: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface RentPayments {
  amount: Numeric;
  contract_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  idempotency_key: string;
  method: string;
  obligation_id: string;
  paid_on: string;
  received_by: string | null;
  reference: string | null;
  void_reason: string | null;
  voided_at: Timestamp | null;
  voided_by: string | null;
}

export interface RolePermissions {
  permission_key: string;
  role_key: string;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  is_system: Generated<boolean>;
  key: string;
  name: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Settings {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface SettlementLines {
  amount: Numeric;
  description: string;
  id: Generated<string>;
  kind: string;
  payment_id: string | null;
  settlement_id: string;
}

export interface SiteEvents {
  hotspot_id: string | null;
  id: Generated<Int8>;
  name: string;
  occurred_at: Generated<Timestamp>;
  property_id: string | null;
  props: Generated<Json>;
  scene_id: string | null;
  scene_slug: string | null;
  session_key: string;
  tour_id: string | null;
}

export interface SocialAssets {
  file_id: string | null;
  id: Generated<string>;
  property_media_id: string | null;
  social_post_id: string;
  sort_order: Generated<number>;
}

export interface SocialPosts {
  approved_at: Timestamp | null;
  approved_by: string | null;
  campaign_id: string | null;
  caption: string;
  channel: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  external_container_id: string | null;
  external_post_id: string | null;
  generated_by: string;
  id: Generated<string>;
  last_error: string | null;
  prompt_version: string | null;
  property_id: string | null;
  published_at: Timestamp | null;
  rejected_reason: string | null;
  scheduled_at: Timestamp | null;
  source_event_id: Int8 | null;
  status: Generated<string>;
  template_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Tags {
  color: string | null;
  id: Generated<string>;
  name: string;
}

export interface Tasks {
  assigned_user_id: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dedupe_key: string | null;
  description: string | null;
  due_at: Timestamp | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  kind: Generated<string>;
  priority: Generated<string>;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface UserBranches {
  branch_id: string;
  user_id: string;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  role_key: string;
  user_id: string;
}

export interface Users {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  failed_logins: Generated<number>;
  full_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  organization_id: string;
  password_hash: string | null;
  phone: string | null;
  public_profile: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  whatsapp_e164: string | null;
}

export interface VirtualTourHotspots {
  content: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  label: string;
  pitch: number;
  scene_id: string;
  sort_order: Generated<number>;
  target_scene_id: string | null;
  updated_at: Generated<Timestamp>;
  yaw: number;
}

export interface VirtualTours {
  cover_file_id: string | null;
  cover_url: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  embed_url: string | null;
  external_url: string | null;
  floor_plan_file_id: string | null;
  floor_plan_height: number | null;
  floor_plan_url: string | null;
  floor_plan_width: number | null;
  guided_scene_ids: Generated<string[]>;
  id: Generated<string>;
  is_demo: Generated<boolean>;
  kind: string;
  property_id: string;
  provider: string | null;
  published_at: Timestamp | null;
  start_scene_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface VirtualTourScenes {
  created_at: Generated<Timestamp>;
  height: number;
  id: Generated<string>;
  initial_pitch: Generated<number>;
  initial_yaw: Generated<number>;
  is_published: Generated<boolean>;
  name: string;
  panorama_file_id: string | null;
  panorama_url: string | null;
  plan_x: number | null;
  plan_y: number | null;
  preview_file_id: string | null;
  preview_url: string | null;
  slug: string;
  sort_order: Generated<number>;
  thumbnail_file_id: string | null;
  thumbnail_url: string | null;
  tour_id: string;
  updated_at: Generated<Timestamp>;
  width: number;
}

export interface WebhookEvents {
  attempts: Generated<number>;
  external_event_id: string;
  id: Generated<string>;
  last_error: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
  signature_valid: boolean;
  status: Generated<string>;
}

export interface DB {
  activities: Activities;
  adjustment_indices: AdjustmentIndices;
  ai_conversations: AiConversations;
  ai_feedback: AiFeedback;
  ai_interactions: AiInteractions;
  ai_knowledge_chunks: AiKnowledgeChunks;
  ai_knowledge_documents: AiKnowledgeDocuments;
  ai_messages: AiMessages;
  appointments: Appointments;
  audit_logs: AuditLogs;
  automation_definitions: AutomationDefinitions;
  automation_errors: AutomationErrors;
  automation_runs: AutomationRuns;
  branches: Branches;
  campaigns: Campaigns;
  contact_addresses: ContactAddresses;
  contact_duplicate_candidates: ContactDuplicateCandidates;
  contact_emails: ContactEmails;
  contact_phones: ContactPhones;
  contact_roles: ContactRoles;
  contact_tags: ContactTags;
  contacts: Contacts;
  content_templates: ContentTemplates;
  conversation_messages: ConversationMessages;
  conversations: Conversations;
  domain_events: DomainEvents;
  external_refs: ExternalRefs;
  feature_flags: FeatureFlags;
  features: Features;
  files: Files;
  index_values: IndexValues;
  integration_credentials: IntegrationCredentials;
  integration_logs: IntegrationLogs;
  integrations: Integrations;
  jobs: Jobs;
  lead_sources: LeadSources;
  leads: Leads;
  locations: Locations;
  login_attempts: LoginAttempts;
  migration_records: MigrationRecords;
  migration_runs: MigrationRuns;
  migration_warnings: MigrationWarnings;
  notes: Notes;
  notifications: Notifications;
  opportunities: Opportunities;
  opportunity_stage_history: OpportunityStageHistory;
  organizations: Organizations;
  outbound_messages: OutboundMessages;
  owner_reports: OwnerReports;
  owner_settlements: OwnerSettlements;
  password_reset_tokens: PasswordResetTokens;
  permissions: Permissions;
  pipeline_stages: PipelineStages;
  pipelines: Pipelines;
  properties: Properties;
  property_agents: PropertyAgents;
  property_documents: PropertyDocuments;
  property_features: PropertyFeatures;
  property_media: PropertyMedia;
  property_operations: PropertyOperations;
  property_owners: PropertyOwners;
  property_price_history: PropertyPriceHistory;
  property_publications: PropertyPublications;
  property_redirects: PropertyRedirects;
  property_status_history: PropertyStatusHistory;
  property_types: PropertyTypes;
  publication_channels: PublicationChannels;
  rate_limit_buckets: RateLimitBuckets;
  rent_adjustments: RentAdjustments;
  rent_obligations: RentObligations;
  rent_payments: RentPayments;
  rental_contract_documents: RentalContractDocuments;
  rental_contract_parties: RentalContractParties;
  rental_contracts: RentalContracts;
  role_permissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  settings: Settings;
  settlement_lines: SettlementLines;
  site_events: SiteEvents;
  social_assets: SocialAssets;
  social_posts: SocialPosts;
  tags: Tags;
  tasks: Tasks;
  user_branches: UserBranches;
  user_roles: UserRoles;
  users: Users;
  virtual_tour_hotspots: VirtualTourHotspots;
  virtual_tour_scenes: VirtualTourScenes;
  virtual_tours: VirtualTours;
  webhook_events: WebhookEvents;
}
